### ISSUE TITLE
Abort Multiple Requests to the same WMS Map Layer

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#382] opened 2021-03-12 10:53 UTC
If a user unchecks a grid filter, and then checks a new value then the same WMS layer is requested twice.
Ideally there would be a mechanism to abort any requests to the same layer so only the latest request is sent. 

https://github.com/compassinformatics/cpsi-mapview/blob/c9338fea016a382c46604ca2cb217c27bea2de9d/app/controller/grid/Grid.js#L199

This is not only applicable to grids but also when zooming in gradually, or with multiple pans in quick succession.
This has been raised at https://github.com/openlayers/openlayers/issues/8425 so this solution could possibly be added to all WMS layers in mapview by default.

**Comment by simonseyock** [comment] 2021-05-17 08:36
I introduced the proposed changes in https://github.com/compassinformatics/cpsi-mapview/pull/402

But I have to admit that I cannot reproduce the problem in the demo client. There are at most 3-4 concurrent requests that finish really quickly. What layers do you use to trigger this problem? Also I did not yet work with the grids and I don't know how to access them. Can you tell me?

**Comment by geographika** [comment] 2021-05-17 11:23
@simonseyock - WMS config sent by email. 
As grids use WFS they shouldn't be affected by this issue. A sample grid is available by right-clicking the Ruins layer:

![image](https://user-images.githubusercontent.com/490840/118480834-0de05780-b713-11eb-878d-064dad24c351.png)

**Comment by simonseyock** [comment] 2021-05-17 12:47
I have to confess that this layer also loads very fast for me. I see that the image source is overwritten at some points, but I do not see any cancelled requests. And after thinking about this I don't know if that is actually what you want :)
If the requests get cancelled they are already sent, and if the server does not support aborting a request (they rarely do, i highly doubt that a normal wms would do that) it would not get you any benefits in regard of server load.

What we can do though is a throttling that only requests wms once every second or something like that. Alternatively only request if no other request is following within a second or so.

**Comment by geographika** [comment] 2021-05-17 13:11
We had some performance issues with some WMS layers which was leading to a large queue of pending requests waiting in the browser. I was thinking cancelling the old ones would take some pressure off the server, but as you say once the request is triggered the server will do the work even if the client request is cancelled. 

The demo app might not be the best example to try and recreate the issue. In more complicated applications a user may turn on 20-30 layers and use the map wheel to zoom in and out. This can build a large queue of pending requests as in the image below (I believe Chrome handles 6 requests to the same server?). All requests have to be processed before getting to the final requests which are the ones the user is interested in. Would cancelling pending WMS (and even WFS) requests on a map extent change event make sense? Once a user has moved the map or changed zoom level those layer images are no longer relevant. 

![image](https://user-images.githubusercontent.com/490840/118492909-d5477a80-b720-11eb-9574-8e5bfed50f96.png)

**Comment by simonseyock** [comment] 2021-05-17 13:31
in that case it might make sense, but you would still have 5 requests per layer that are cued but not needed.

I added some code to debounce layer requests. That means that the layer is only requested if it is not requested again for some given time. This could lead to the users having to wait for some time till the requests start, but in the end this would be much faster. Do you think this would be an option?

I made it configurable for wms layers in the `layers.conf` via a property `debounce` that can be set to a value in miliseconds.

**Comment by simonseyock** [comment] 2021-05-17 13:36
It is already merged into the open PR. It does work, and in my opinion this is ok if not all layers are configured this way - so some layers load immediately and others later. It does not feel much different from normal usage.

**Closed** 2021-05-21 17:30 UTC
Labels: enhancement
